### ISSUE TITLE
clang test failures

### ISSUE THREAD

**Issue by pgdr** [Ensembles/ert#1252]
Several tests fail on clang:

**ert_util_work_area** (failed),
**config_path_elm** (failed).  Path strings differ:

```
...T/travis/test/config_path_elm/...
...T//travis/test/config_path_elm/...
```

**enkf_analysis_config_analysis_load** (failed)

```
Failed to load library:rml_enkf.so Error:dlopen(rml_enkf.so, 2): image not found
** Warning: failed to load module from rml_enkf.so.
Failed to load library:rml_enkf.so Error:dlopen(rml_enkf.so, 2): image not found
** Warning: failed to load module from rml_enkf.so.
** Warning:: Do not have enough information to select a history source
/Users/travis/build/Ensembles/ert/libenkf/tests/enkf_analysis_config_analysis_load.c:39 => assert( true ) failed
```

**enkf_workflow_job_test_version** (failed)

```
** Warning keyword:This not recognized when parsing:/Users/travis/build/Ensembles/ert/libenkf/tests/data/workflow_jobs/CONF2 ---
** Warning keyword:instead not recognized when parsing:/Users/travis/build/Ensembles/ert/libenkf/tests/data/workflow_jobs/CONF2 ---
** Warning: failed to add workflow job:CONF2 from:/Users/travis/build/Ensembles/ert/libenkf/tests/data/workflow_jobs/CONF2
/Users/travis/build/Ensembles/ert/libenkf/tests/enkf_workflow_job_test_version.c:65 => assert( true ) failed
```

**python.tests.core.cwrap** (exception)

```
python(10402,0x7fff7c3d6000) malloc: *** error for object 0x6f2ed90: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort called from: util_abort_signal (/Users/travis/build/Ensembles/ert/libert_util/src/util.c:4894)
Error message: Program received signal:6
```

**python.tests.core.cwrap.metacwrap** (exception)

```
The type used as return type: test_stringlist is not registered as a return type.
Abort called from: util_abort_signal (/Users/travis/build/Ensembles/ert/libert_util/src/util.c:4894)
Error message: Program received signal:11
```

**python.tests.core.util.path_context** (failed)

```
FAIL: test_chdir (core.util.test_path_context.PathContextTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/Ensembles/ert/build/python/tests/core/util/test_path_context.py", line 21, in test_chdir
    self.assertEqual( os.getcwd() , "/tmp/pc")
AssertionError: '/private/tmp/pc' != '/tmp/pc'
```

**python.tests.ecl.ecl_kw** (failed)

```
ERROR: test_kw_write (ecl.test_ecl_kw.KWTest)
Traceback (most recent call last):
  File "/Users/travis/build/Ensembles/ert/build/python/tests/ecl/test_ecl_kw.py", line 149, in test_kw_write
    kw4 = EclKW.fread(fortio)
  File "/Users/travis/build/Ensembles/ert/build/python/ert/ecl/ecl_kw.py", line 346, in fread
    return cls._fread_alloc( fortio )
  File "/Users/travis/build/Ensembles/ert/build/python/ert/cwrap/prototype.py", line 136, in __call__
    return self._func(*args)
  File "/Users/travis/build/Ensembles/ert/build/python/ert/cwrap/prototype.py", line 114, in returnFunction
    return return_type(result)
  File "/Users/travis/build/Ensembles/ert/build/python/ert/ecl/ecl_kw.py", line 148, in createPythonObject
    raise ValueError("Failed to create EclKW instance")
ValueError: Failed to create EclKW instance
```

**python.tests.ert.enkf.time_map** (exception)

```
Abort called from: util_make_datetime_utc (/Users/travis/build/Ensembles/ert/libert_util/src/util.c:3307)
Error message: util_make_datetime_utc: failed to make a time_t instance of 10/10/ 200  00:00:00 - aborting
```

**Comment by pgdr** [comment]
Reopen at [Statoil/libecl](https://github.com/Statoil/libecl) if still an issue.
